# Generated by Django 5.1.6 on 2025-02-24 22:55

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=home.models.car_photo_upload_to)),
                ('mark', models.CharField(default='Unknown', max_length=100)),
                ('model', models.CharField(default='Unknown', max_length=100)),
                ('price', models.CharField(default='0.00', max_length=11)),
                ('miles', models.CharField(default='0', max_length=11)),
                ('engine', models.CharField(default='Unknown', max_length=100)),
                ('information', models.TextField(blank=True, null=True)),
                ('body', models.CharField(default='Sedan', max_length=50)),
                ('fuel_type', models.CharField(default='Gasoline', max_length=50)),
                ('year', models.IntegerField(default=2021)),
                ('transmission', models.CharField(default='Automatic', max_length=50)),
                ('drive_type', models.CharField(default='Rear-Wheel Drive', max_length=50)),
                ('condition', models.CharField(default='Used', max_length=50)),
                ('engine_size', models.CharField(default='N/A', max_length=50)),
                ('doors', models.IntegerField(default=4)),
                ('people', models.IntegerField(default=4)),
                ('cylinders', models.IntegerField(default=4)),
                ('color', models.CharField(default='Red', max_length=50)),
                ('vin', models.CharField(default='Unknown', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=home.models.car_photo_upload_to)),
                ('order', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='home.car')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
