# Generated by Django 5.1.6 on 2025-02-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='stock',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
