# Generated by Django 5.1.6 on 2025-02-27 22:19

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=500, upload_to=home.models.car_photo_upload_to),
        ),
    ]
