# Generated by Django 5.1.2 on 2024-10-10 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('mark', models.CharField(default='Unknown', max_length=100)),
                ('model', models.CharField(default='Unknown', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('miles', models.IntegerField(default=0)),
                ('engine', models.CharField(default='Unknown', max_length=100)),
                ('information', models.TextField(blank=True, null=True)),
                ('body', models.CharField(default='Sedan', max_length=50)),
                ('fuel_type', models.CharField(default='Gasoline', max_length=50)),
                ('year', models.IntegerField(default=2021)),
                ('transmission', models.CharField(default='Automatic', max_length=50)),
                ('drive_type', models.CharField(default='Rear-Wheel Drive', max_length=50)),
                ('condition', models.CharField(default='Used', max_length=50)),
                ('engine_size', models.FloatField(default=2.0)),
                ('doors', models.IntegerField(default=4)),
                ('cylinders', models.IntegerField(default=4)),
                ('color', models.CharField(default='Red', max_length=50)),
                ('vin', models.CharField(default='Unknown', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='home.car')),
            ],
        ),
    ]
